-
  # Install build-essential
  hosts: localhost
  connection: local
  tags:
  - install_generator_plantuml
  - install_generator_asciidoctor
  - install_doctools

  tasks:
  - name: Install build-essential
    apt:
      name: build-essential
      update_cache: yes

-
  # Install doctools
  hosts: localhost
  connection: local
  gather_facts: yes
  tags:
  - install_generator_asciidoctor
  - install_doctools

  vars:
    asciidoctor_version: 2.0.18
    asciidoctor_version_expected: "{{ asciidoctor_version }}[.]"

  tasks:
  - name: Install Ruby
    apt:
      name: ruby-full
      update_cache: yes
  - name: Run gem install for asciidoctor
    shell:
      cmd: "gem install asciidoctor -v {{ asciidoctor_version }}"
  - name: install asciidoctor-bibtex as ruby gem
    shell: gem install asciidoctor-bibtex
  - name: install asciidoctor-diagram as ruby gem
    shell: gem install asciidoctor-diagram
  - name: install asciidoctor-pdf as ruby gem
    shell: gem install asciidoctor-pdf
  - name: install asciidoctor-revealjs as ruby gem
    shell: gem install asciidoctor-revealjs
  - name: Get asciidoctor version
    shell: asciidoctor --version | grep Asciidoctor | sed 's/[[:alpha:]|(|[:space:]]//g' | sed 's/[*~://]//g'
    register: installed_asciidoctor_version
  - name: Display asciidoctor version
    debug:
      msg: "ASCII Doctor = {{ installed_asciidoctor_version.stdout }}"
  - name: Test asciidoctor version
    fail:
      msg: "ASCII Doctor Version Error: Expected {{ asciidoctor_version_expected }} | Found {{ installed_asciidoctor_version.stdout }}"
    when: installed_asciidoctor_version.stdout != asciidoctor_version_expected

